{% set name = "vvm" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vvm-{{ version }}.tar.gz
  sha256: a1474915b12e0084299d2c7fe7d72434fa99c00ebb117e400756a5d7e0edac2a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-markdown
  run:
    - python >={{ python_min }},<4.0
    - requests >=2.19.0,<3
    - semantic_version >=2.8.1,<3

test:
  imports:
    - vvm
    - vvm.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vyperlang/vvm
  summary: Vyper version management tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
